version: '3'
services:

  nginx:
    image: nginx:1.19-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/thangtran/Projects:/var/www/html
    networks:
      - appnet

  php:
    build: php
    volumes:
      - /home/thangtran/Projects:/var/www/html
      - ./xprofiler:/tmp/snapshots
    networks:
      - appnet

  db:
    image: mariadb:10.4
    command: --init-file /home/init.sql
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_home:/home
    ports:
      - 33067:3306
    environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: magento2
       MYSQL_USER: magento2
       MYSQL_PASSWORD: magento2
    networks:
      - appnet

  cache:
    image: redis:5.0-alpine
    tty: true
    networks:
      - appnet

  fpc:
    image: redis:5.0-alpine
    tty: true
    networks:
      - appnet

volumes:
  db_data:
    driver: "local"
networks:
  appnet:
    driver: "bridge"
